### ISSUE TITLE
Updating the new version

### ISSUE THREAD

**Issue by nguyentrungchau1996** [cra-template/pwa#14]
At the moment, I'm using React 16.8 on my project. How could I use 'cra-template-pwa-typescript' for my React version? I found the latest React version it supports the service worker better the older. Thank you so much!

**Comment by jeffposnick** [comment]
If you're using an older version of `c-r-a`, prior to version 4.x, there's unfortunately no automatic update path to using this template. 

You can [scaffold out a new project](https://create-react-app.dev/docs/making-a-progressive-web-app/) via

```
npx create-react-app my-app --template cra-template-pwa-typescript
```

**Comment by nguyentrungchau1996** [comment]
Thank you @jeffposnick
