### ISSUE TITLE
Open to PR for Create React App PWA offline fallback page only?

### ISSUE THREAD

**Issue by sidonaldson** [cra-template/pwa#17]
Hey @jeffposnick 

I have a client with a CRA site who wants to install a PWA with only a fallback "you're offline" page.

In which case I can simply override the contents of service-worker.ts/js

I wondered if it's a common request? If so I'm happy to work on a PR to add it as a cra-template? 

The below is a basic working version (assuming `/public/offline.html` exists

e.g. cra-template-pwa-fallback-page & cra-template-pwa-fallback-page-typescript

```
/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

declare const self: ServiceWorkerGlobalScope;

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const ignored = self.__WB_MANIFEST;

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async function () {
      const cache = await caches.open("static-v1");
      await cache.addAll(["offline.html"]);
    })()
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async function () {
      if (self.registration.navigationPreload) {
        await self.registration.navigationPreload.enable();
      }
    })()
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  // Always bypass for range requests, due to browser bugs
  if (request.headers.has("range")) return;
  event.respondWith(
    (async function () {
      const cachedResponse = await caches.match(request);
      if (cachedResponse) return cachedResponse;
      try {
        const response = await event.preloadResponse;
        if (response) return response;
        return await fetch(request);
      } catch (err) {
        if (request.mode === "navigate") {
          return caches.match("offline.html");
        }
        throw err;
      }
    })()
  );
});

export {};
```

**Comment by jeffposnick** [comment]
It's definitely a valid use case, but at the same time, I don't think we can commit too many different alternative service workers to this repo without it being confusing for developers.

The general philosophy behind what we have checked in as part of this template is to match the behavior implemented in the previous `c-r-a` service worker by default (making it easier for existing users to transition to this), but at the same time, give developers control over implementing something like the code you just shared if they want to.

So, my approach would be not to check in the code for an offline fallback page. Thank you, though!

**Comment by sidonaldson** [comment]
ah shame. I respectfully disagree. I don't think there can be any confusion. One is for serving a single static offline page and the other is true PWA offline caching.

**Comment by jeffposnick** [comment]
By the way, I'd definitely encourage you to publish your desired template to `npm`! You can follow the steps at https://create-react-app.dev/docs/custom-templates/ and then developers who find your template can use it to get the starting point that you describe.

I just don't think that creating multiple starting points in this repo makes the most sense.
