### ISSUE TITLE
Customize the name of the service-worker file?

### ISSUE THREAD

**Issue by danielo515** [cra-template/pwa#20]
Hello,
I'm wondering if it may be possible to customize the name of the generated service worker.
I have some libraries that require an specific service worker name

**Comment by jeffposnick** [comment]
To change this directly, you'd need access to the underlying `webpack` configuration to do that, which is only possible with `create-react-app` if you [eject](https://create-react-app.dev/docs/available-scripts/#npm-run-eject).

Alternatively, after the `c-r-a` build process completes you could attempt to run an additional command that would rename the generated service worker file, but I'm not sure what the best way to automate that would be.

(Which libraries are you using that require a specific service worker name, by the way?)

**Comment by danielo515** [comment]
> (Which libraries are you using that require a specific service worker name, by the way?)

firebase FCM will automatically try to register a service worker with the name `firebase-messaging-sw.js`. Trying to change the name after build should be doable with a bash script on a postbuild script. Thanks.

**Comment by jeffposnick** [comment]
You can use FCM with an existing top-level service worker; I believe you need to call `importScripts()` from that top-level service worker (like the one generated in `c-r-a`) to pull in the FCM code, and then something with:

- https://firebase.google.com/docs/reference/js/firebase.messaging.Messaging#gettoken
- https://firebase.google.com/docs/cloud-messaging/js/receive#web-v8
 
to pass through the registration info? I'm not 100% sure of all the steps, but it is possible.

**Comment by danielo515** [comment]
Yes, you can get the registration object and pass it down to the getToken method and it will use that service worker. However, that means that I will have to handle the registration and keep the correct reference somewhere.
While this is not very problematic but I am not using the PWA template, which means that I don't have the registration scripts and that stuff. But that is just the smallest problem, the main problem is that it is too early for my project to be cached by a service worker and all the problems that has. I want every release to reach all my users as soon as possible.

All I wanted from CRA was to compile my SW from typescript and bundle the proper imports into the file (i18n and some libs that I may need) without any caching, but seems that such thing is not possible.
I tried deactivating the caching according to docs and the generated SW is still huge, I don't understand what it includes.

**Comment by jeffposnick** [comment]
You don't have to use the `c-r-a` template for PWAs in that case. You can just create your own bare-bones service worker file containing whatever you want and... I am not actually sure how to tell `c-r-a` to compile it, but that's more of a question for the `c-r-a` project itself. But once you have the service worker compiled, it can be registered from your main web app via `navigator.serviceWorker.register('my-sw.js')`.

Using this PWA template is optional, and intended for folks who do want that Workbox-based precaching, which does require deep integration with your underlying `webpack` build.
