### ISSUE TITLE
Typescript version of serviceWorkerRegistration refers to Javascript file

### ISSUE THREAD

**Issue by Ark-kun** [cra-template/pwa#26]
I wonder whether this is an issue.

The file in the bundle is called `service-worker.ts`, but the code refers to `service-worker.js`

```typescript
export function register() {
  if (process.env.NODE_ENV === "production" && "serviceWorker" in navigator) {
    const swUrl = `${process.env.PUBLIC_URL}/service-worker.js`;
    window.addEventListener("load", async () => {
      if (isLocalhost) await validateLocalServer(swUrl);
      registerSW(swUrl);
    });
  }
}
```

**Comment by jeffposnick** [comment]
Browsers can't run TypeScript code. TypeScript code needs to be compiled into JavaScript code before its runnable as a service worker. This is done via `c-r-a`'s production build, and during that process, the file extension of `.js` is used to reflect the fact that the compiled file contains JavaScript code.
