### ISSUE TITLE
How do I rename the service-worker file

### ISSUE THREAD

**Issue by haggen** [cra-template/pwa#7]
Hi, I had a previous PWA setup but the service-worker file was called `sw.js` and now I can't make it register the new one. I tried simply renaming the file to `sw.ts` (I'm using TypeScript) and changing the `swUrl` variable in `serviceWorkerRegistration` file but it didn't work.

Any hints? Thanks.

**Comment by jeffposnick** [comment]
The service worker name isn't customizable, as it's one of the options that are used in the [configuration from the main `c-r-a` project](https://github.com/facebook/create-react-app/blob/027b03ba8d689e619a912ed0d72c3a11ef22ac2f/packages/react-scripts/config/paths.js#L75). Without being able to customize the configuration, you can't change the name.

If you have a previously deployed service worker with a different URL, and want to transition to the new service worker URL,  you should take the following two steps:

- Create and deploy a "[kill switch](https://stackoverflow.com/a/38980776/385997)" service worker with your old URL.
- Deploy your new service worker and ensure that the URL you use for service worker registration corresponds to the new URL.

If you follow both those steps, then both repeat visitors and new visitors will (eventually) end up with the correct service worker with the new URL. It can take two navigation requests for repeat visitors to get the complete update, as the first navigation request will result in the "kill switch" service worker being installed, and the second navigation request will result in the new service worker being installed.

**Comment by haggen** [comment]
@jeffposnick Thank you for the thoughtful answer! I ended up making a rewrite from `/sw.js` to `/service-worker.js` and using the `unregister()` call. In my case PWA wasn't really worth the trouble.
